### ISSUE TITLE
Segmentation fault (core dumped)  

### ISSUE THREAD

**Issue by RiceNeurons** [open-ephys-GUI-binaries/linux-64#3]
I keep getting this error message when I attempt to load the parameters file.  Given information in Terminal it appears the file is loading correctly until "Adding electrode with 4 channels." It then gives me this error message.  Additionally, several times today I've received the error "Interruped system call".  

Please advise.

Thank you!
Sarah

**Comment by jsiegle** [comment]
Hi Sarah, can you post the parameters file? Also, can you try re-creating the same signal chain, saving a new file, and re-loading? It could be a version compatibility issue.

**Comment by RiceNeurons** [comment]
Thanks Josh,

Thank you for your response!  It turns out the commutator was  
broken...  I really appreciate the prompt response and help!

Best,
Sarah


Quoting Josh Siegle <notifications@github.com>:

> Hi Sarah, can you post the parameters file? Also, can you try  
> re-creating the same signal chain, saving a new file, and  
> re-loading? It could be a version compatibility issue.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/open-ephys-GUI-binaries/linux-64/issues/3#issuecomment-73577658


-- 
Sarah Eagleman, Ph.D.
Postdoctoral Research Fellow
Kemere Lab
Electrical and Computer Engineering Department
BioScience Research Collaborative - Rice University
sarah.eagleman@rice.edu
